config/routes.rb
Rails.application.routes.draw do
    root to:'pokemon_cards#index'

    get 'pokemon_cards/backups', to: 'pokemon_cards#backups'
    post 'pokemon_cards/delete_all', to: 'pokemon_cards#delete_all'

    resources :pokemon_cards, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemonCard.rb
class PokemonCard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_cards_controller.rb
class PokemonCardsController < ApplicationController
    before_action :set_pokemon_cards, only: [:index, :backups]

    def index
        if @pokemon_cards.length > 0
            flash[:notice] = nil
            redirect_to pokemon_cards_backups_path
        else
            render 'index'
        end
    end
    
    def backups
        card = pokemon_card_params[:card]
        if card 
            @pokemon_cards = PokemonCard.where('name = ? or hp = ? or rarity = ?', card, card, card)
        end
    end

    def create
        CreateBackupWorker.perform_now
        redirect_to pokemon_cards_backups_path, notice: 'Loading Images'
    end

    def delete_all
        PokemonCard.delete_all

        redirect_to root_path
    end

    private

    def set_pokemon_cards
      @pokemon_cards = PokemonCard.all
    end

    def pokemon_card_params
        params.permit(:card)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<div class="container p-2">
    <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand">Pokemon Cards</a>
    <%= button_to "Create Backup", pokemon_cards_path, remote: true%>
    <%= button_to "Purge Backup", pokemon_cards_delete_all_path, remote: true, method: :post %>
   
    <%= form_tag pokemon_cards_backups_path, method: :get, if: 'serach_form' do %>
        <%= text_field_tag :card%>
        <%= submit_tag 'Search'%>
    <% end %>
    </form>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>

  <header>
    <%= render 'layouts/navigation' %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.js.erb
$(function() {
  $("#search_form input").keyup(function() {
    $.get($("#search_form").attr("action"), $("#search_form").serialize(), null, "script");
    return false;
  });
});

app/views/pokemon_cards/_cards.html.erb
<div class="container p-5">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Hit Point</th>
                <th scope="col">Rarity</th>
            </tr>
        </thead>
        <tbody>
        <% unless @pokemon_cards.empty? %>
            <% @pokemon_cards.each do |card| %>
            <tr>
                <td><%= card.name %></td>
                <td><%= card.hp %></td>
                <td><%= card.rarity %></td>
            </tr>
            <% end %>
        <% else %>
            <tr>
            <td >No cards found</td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/pokemon_cards/backups.html.erb
<div class="container">
    <div class="container">
        <div id="cards">
            <%= render 'cards' %>
        </div>
    </div>
</div>

app/views/pokemon_cards/backups.js.erb
$("#cards").html("<%= escape_javascript(render("cards")) %>");

app/views/pokemon_cards/index.html.erb
<div class="container">
    <div class="row p-5">
        <h2>Click on Create Backup button to get cards.</h2>
    </div>
</div>